# Generated by Django 6.1 on 2026-09-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_avatar_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "User")],
                default="member",
                help_text="Defines user level permissions.",
                max_length=20,
            ),
        ),
    ]
