# Generated by Django 6.1 on 2026-09-27 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_projectdeletionrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="incharges",
            field=models.ManyToManyField(
                blank=True,
                related_name="incharge_projects_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
